services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports: ["${POSTGRES_PORT:-5432}:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  airflow:
    image: apache/airflow:2.9.3
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@${AIRFLOW_DB_HOST}:${AIRFLOW_DB_PORT}/${AIRFLOW_DB_NAME}
      AIRFLOW__DATABASE__LOAD_DEFAULT_CONNECTIONS: "False"
    command: >
      bash -lc "
        airflow db upgrade &&
        airflow users create
          --username ${AIRFLOW_ADMIN_USER}
          --password ${AIRFLOW_ADMIN_PASSWORD}
          --firstname Admin
          --lastname User
          --role Admin
          --email ${AIRFLOW_ADMIN_EMAIL} || true &&
        airflow webserver & airflow scheduler
      "
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - airflow_home:/usr/local/airflow
    ports: ["${AIRFLOW_PORT:-8080}:8080"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  minio:
    image: quay.io/minio/minio:RELEASE.2024-06-13T22-53-53Z
    command: server /data --console-address ":${MINIO_CONSOLE_PORT:-9001}"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 10

  # MLflow tracking server
  mlflow:
    image: bitnami/mlflow:2
    environment:
      # Backend store (simple local SQLite file in the container volume)
      MLFLOW_BACKEND_STORE_URI: sqlite:////mlflow/mlflow.db
      # Artifacts to MinIO (S3-compatible)
      MLFLOW_DEFAULT_ARTIFACT_ROOT: s3://mlflow
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL:-http://minio:9000}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - mlflow_data:/mlflow
    ports:
      - "${MLFLOW_PORT:-5000}:5000"

  # Apache Superset (for BI)
  superset:
    image: apache/superset:latest
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - superset_home:/app/superset_home
    ports:
      - "${SUPERSET_PORT:-8088}:8088"
    command: >
      bash -lc "
        superset db upgrade &&
        superset fab create-admin
          --username ${SUPERSET_ADMIN_USERNAME}
          --firstname Admin
          --lastname User
          --email ${SUPERSET_ADMIN_EMAIL}
          --password ${SUPERSET_ADMIN_PASSWORD} || true &&
        superset init &&
        gunicorn -w 2 -k gevent --timeout 60 -b 0.0.0.0:8088 'superset.app:create_app()'
      "

volumes:
  pgdata:
  airflow_home:
  minio_data:
  mlflow_data:
  superset_home: